### numpy

In [5]:
import numpy as np

x = [1,2,3,4,5,6]
print(x)
arr = np.array(x)
print(arr)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [6]:
arr1 = np.array([2,3,4,5])
print(arr1)

[2 3 4 5]


In [9]:
print(type(x))
print(type(arr1))

<class 'list'>
<class 'numpy.ndarray'>


In [13]:
arr2 = np.array([1,2,3,4,5])
print(type(arr[1:4]))
print(arr[1:4])

<class 'numpy.ndarray'>
[2 3 4]


In [ ]:
y = [[1,2,3],[4,5,6]]
arr3 = np.array(y)
print(arr3)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr3[1,2])
print(arr3.shape)
# arr2 = np.array([1,2,3,4,5])
print(arr2.shape)

6
(2, 3)
(5,)


In [22]:
arr4 = np.array([1,2,3,4,5,6])
arr5 = arr4.reshape(3,2)
print(arr5)

[[1 2]
 [3 4]
 [5 6]]


In [27]:
x1 = [1,2,3,4]
y2 = [4,5,6,7]

print(x1+y2)

[1, 2, 3, 4, 4, 5, 6, 7]


In [30]:
arr11 = np.array(x1)
arr12 = np.array(y2)

print(arr11*arr12)

[ 4 10 18 28]


In [31]:
print(arr11.dtype)

int64


In [34]:
arr13 = np.array([1,2,3])
print(arr13.dtype)

arr13_float = arr13.astype('float64')
print(arr13_float)
print(arr13_float.dtype)

int64
[1. 2. 3.]
float64


In [45]:
arr14 = np.arange(12)
print(arr14, arr14.dtype)
arr15 = arr14.reshape(3,-1)
print(arr15)

[ 0  1  2  3  4  5  6  7  8  9 10 11] int64
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr20 = np.arange(1,10)
print(arr20)
arr21 = arr20.reshape(3,3)
print(arr21)

# [0:2,0:2] 
arr31 = arr21[0:2,0:2]
print(arr31, arr31.shape)

#[1:3,0:3]
#[1:3,:]
#[:,:]
#[:2,:1]
#[:2,0]

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]] (2, 2)


### 동물별 평균체온과 최대 체중구하기

In [61]:
import numpy as np

# 체온, 심박수, 체중(kg)
data = np.array([
    [38.5,80,35], #개
    [39.1,90,20], #고양이
    [36.8,60,400]   #말
])

ani = np.array(["개","고양이","말"])

# 체온, 심박수, 체중 평균값
avg_value = data.mean(axis=0)

print(avg_value)

weight = data[:,2]
print(weight)

max_weight = data[:,2].max()
print(max_weight)

max_ani = ani[data[:,2].argmax()]
print(max_ani)


print("동물별 평균수치 : ",avg_value )
print("가장무거운동물 : ",max_ani, f'{max_weight}kg' )




[ 38.13333333  76.66666667 151.66666667]
[ 35.  20. 400.]
400.0
말
동물별 평균수치 :  [ 38.13333333  76.66666667 151.66666667]
가장무거운동물 :  말 400.0kg


### 곤충 [날개수, 다리수, 몸길이(cm)]

In [69]:

data = np.array([
    [2,6,1.2],
    [4,6,3.4],
    [0,6,0.8],
    [0,8,2.0]
])

insects = np.array(["나비","잠자리","개미","거미"])

# 다리가 6개인 곤충만 추출
legs = data[data[:,1] == 6]
print(legs)

# 평균 몸길이 구하기
mean_length = data[:,2].mean()
print(mean_length)
print("곤충 평균 몸길이 : ",round(mean_length,2),"cm")

# 날개가 없는 곤충출력
no_wings = insects[data[:,0] == 0]
print("날개없는 곤충 : ",no_wings)



[[2.  6.  1.2]
 [4.  6.  3.4]
 [0.  6.  0.8]]
1.8499999999999999
곤충 평균 몸길이 :  1.85 cm
날개없는 곤충 :  ['개미' '거미']
