In [2]:
!pip install tensorflow

In [5]:
from warnings import filterwarnings
filterwarnings("ignore")

import tensorflow as tf
import numpy as np

In [40]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import mse
from tensorflow.keras.optimizers import Adam

1. 단층퍼셉트론으로 0r게이트 구현

|x1|x2|y|
|---|---|---|
|0|0|0|
|1|0|1|
|0|1|1|
|1|1|1|

In [6]:
data = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]
])

label = np.array([0,1,1,1])


In [10]:
#모델구성
# model = tf.keras.Sequential()
# model.add(tf.keras.layers.Dense(1,input_shape=(2,)))

model = Sequential()
model.add(Dense(1, input_shape=(2,)))

In [15]:
#컴파일
model.compile(
    # optimizer="sgd"
    optimizer=SGD(),
    loss=mse,
    metrics=["acc"]
)

In [14]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
#모델학습
model.fit(data,label,epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 296ms/step - acc: 1.0000 - loss: 0.0862
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 1.0000 - loss: 0.0861
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 1.0000 - loss: 0.0859
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 1.0000 - loss: 0.0857
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 1.0000 - loss: 0.0856
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 1.0000 - loss: 0.0854
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 1.0000 - loss: 0.0853
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 1.0000 - loss: 0.0851
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 1.0000 - loss: 0.0850
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 1.0000 - loss: 0.0848
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 1.0000 - loss: 0.0847
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 1.0000 - loss: 0.0845
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/st

In [17]:
model.get_weights()

[array([[0.54646295],
        [0.5386022 ]], dtype=float32),
 array([0.19955036], dtype=float32)]

In [18]:
#모델평가
model.evaluate(data,label)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - acc: 1.0000 - loss: 0.0635


[0.06347492337226868, 1.0]

In [19]:
#모델예측
result = model.predict(data)
print(result)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[[0.19955036]
 [0.7460133 ]
 [0.7381525 ]
 [1.2846155 ]]


### 2. 단층 퍼셉트론 and 게이트

|x1|x2|y|
|---|---|---|
|0|0|0|
|1|0|0|
|0|1|0|
|1|1|1|



In [34]:
data = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]
])

label = np.array([0,0,0,1])

In [35]:
model = Sequential()
model.add(Dense(1, input_shape=(2,)))

In [36]:
model.compile(
    optimizer=SGD(),
    loss=mse,
    metrics=["acc"]
)

In [30]:
model.fit(data,label,epochs=500,verbose=0)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step - acc: 0.7500 - loss: 1.4187
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - acc: 0.7500 - loss: 1.3767
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.7500 - loss: 1.3370
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.7500 - loss: 1.2995
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.7500 - loss: 1.2640
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.7500 - loss: 1.2305
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.7500 - loss: 1.1988
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.7500 - loss: 1.1687
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7500 - loss: 1.1403
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.7500 - loss: 1.1133
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.7500 - loss: 1.0878
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - acc: 0.7500 - loss: 1.0635
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/st

In [31]:
model.get_weights()

[array([[ 0.09570339],
        [-0.08189154]], dtype=float32),
 array([0.49180847], dtype=float32)]

In [32]:
model.evaluate(data,label)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - acc: 0.5000 - loss: 0.2540


[0.2539680004119873, 0.5]

In [33]:
print(model.predict(data))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[[0.49180847]
 [0.58751184]
 [0.40991694]
 [0.5056203 ]]


## 3. xor 게이트

In [37]:
data = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]
])

label = np.array([0,1,1,0])

In [41]:
model = Sequential()
model.add(Dense(32, input_shape=(2,),activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer=Adam(),
    loss=mse,
    metrics=["acc"]
)



In [42]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 32)             │            96 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 129 (516.00 B)

 Trainable params: 129 (516.00 B)

 Non-trainable params: 0 (0.00 B)

In [43]:
model.fit(data,label,epochs=500,verbose=1)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 565ms/step - acc: 0.7500 - loss: 0.2375
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.5000 - loss: 0.2371
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - acc: 0.5000 - loss: 0.2365
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.2361
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - acc: 0.7500 - loss: 0.2356
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.7500 - loss: 0.2352
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.7500 - loss: 0.2347
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 0.7500 - loss: 0.2343
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.7500 - loss: 0.2338
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.7500 - loss: 0.2334
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - acc: 0.7500 - loss: 0.2329
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 0.7500 - loss: 0.2325
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/st

In [44]:
model.evaluate(data,label)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - acc: 1.0000 - loss: 0.0327


[0.03274286910891533, 1.0]

In [45]:
print(model.predict(data))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
[[0.27601656]
 [0.8655618 ]
 [0.8627581 ]
 [0.13370624]]
