In [14]:
import tensorflow as tf
import numpy as np

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import mse
from tensorflow.keras.optimizers import Adam

1. 단층퍼셉트론으로 0r게이트 구현1

|x1|x2|y|
|---|---|---|
|0|0|0|
|1|0|1|
|0|1|1|
|1|1|1|

In [16]:
data = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]
])

label = np.array([0,1,1,1])

In [17]:
model = Sequential()
model.add(Dense(1, input_shape=(2,)))


In [33]:
model.compile(
    optimizer=Adam(),
    loss=mse,
    metrics=['acc']
)

In [34]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
model.fit(data,label,epochs=500,verbose=0)

In [36]:
model.get_weights()

[array([[0.5],
        [0.5]], dtype=float32),
 array([0.25], dtype=float32)]

In [28]:
model.get_weights()

[array([[0.49701756],
        [0.49682906]], dtype=float32),
 array([0.25364947], dtype=float32)]

In [29]:
print(model.predict(data))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
[[0.25364947]
 [0.75066704]
 [0.7504785 ]
 [1.2474961 ]]


In [37]:
print(model.predict(data))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
[[0.25]
 [0.75]
 [0.75]
 [1.25]]


2. xor 게이트

In [39]:
data = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]
])

label = np.array([0,1,1,0])

In [43]:
model = Sequential()
model.add(Dense(32,input_shape=(2,),activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(
    optimizer=Adam(),
    loss=mse,
    metrics=['acc']
)

In [44]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 32)             │            96 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 129 (516.00 B)

 Trainable params: 129 (516.00 B)

 Non-trainable params: 0 (0.00 B)

In [45]:
model.fit(data,label,epochs=500,verbose=0)

In [46]:
model.evaluate(data,label)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 314ms/step - acc: 1.0000 - loss: 0.0356


[0.035607628524303436, 1.0]

In [47]:
print(model.predict(data))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
[[0.20979996]
 [0.81732166]
 [0.81854975]
 [0.1792175 ]]
